"""Add status to Report

Revision ID: 7deafd387180
Revises: 93709ffc5fe6
Create Date: 2024-06-21 07:22:48.697757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7deafd387180'
down_revision = '93709ffc5fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('status', sa.String(length=50), nullable=False, server_default='Pending'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'status')
    # ### end Alembic commands ###
