"""Add status to Report

Revision ID: 93709ffc5fe6
Revises: 7a0c4f4d365c
Create Date: 2024-06-21 07:19:03.760045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93709ffc5fe6'
down_revision = '7a0c4f4d365c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
